# Generated by Django 2.2a1 on 2019-02-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone_number', models.IntegerField()),
                ('number_people', models.IntegerField()),
            ],
        ),
    ]
